// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/ArrowPrimitive.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.ArrowPrimitive)
pub struct ArrowPrimitive {
    // message fields
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.pose)
    pub pose: ::protobuf::MessageField<super::Pose::Pose>,
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.shaft_length)
    pub shaft_length: f64,
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.shaft_diameter)
    pub shaft_diameter: f64,
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.head_length)
    pub head_length: f64,
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.head_diameter)
    pub head_diameter: f64,
    // @@protoc_insertion_point(field:foxglove.ArrowPrimitive.color)
    pub color: ::protobuf::MessageField<super::Color::Color>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.ArrowPrimitive.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ArrowPrimitive {
    fn default() -> &'a ArrowPrimitive {
        <ArrowPrimitive as ::protobuf::Message>::default_instance()
    }
}

impl ArrowPrimitive {
    pub fn new() -> ArrowPrimitive {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Pose::Pose>(
            "pose",
            |m: &ArrowPrimitive| { &m.pose },
            |m: &mut ArrowPrimitive| { &mut m.pose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "shaft_length",
            |m: &ArrowPrimitive| { &m.shaft_length },
            |m: &mut ArrowPrimitive| { &mut m.shaft_length },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "shaft_diameter",
            |m: &ArrowPrimitive| { &m.shaft_diameter },
            |m: &mut ArrowPrimitive| { &mut m.shaft_diameter },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "head_length",
            |m: &ArrowPrimitive| { &m.head_length },
            |m: &mut ArrowPrimitive| { &mut m.head_length },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "head_diameter",
            |m: &ArrowPrimitive| { &m.head_diameter },
            |m: &mut ArrowPrimitive| { &mut m.head_diameter },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "color",
            |m: &ArrowPrimitive| { &m.color },
            |m: &mut ArrowPrimitive| { &mut m.color },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ArrowPrimitive>(
            "ArrowPrimitive",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ArrowPrimitive {
    const NAME: &'static str = "ArrowPrimitive";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pose)?;
                },
                17 => {
                    self.shaft_length = is.read_double()?;
                },
                25 => {
                    self.shaft_diameter = is.read_double()?;
                },
                33 => {
                    self.head_length = is.read_double()?;
                },
                41 => {
                    self.head_diameter = is.read_double()?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pose.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.shaft_length != 0. {
            my_size += 1 + 8;
        }
        if self.shaft_diameter != 0. {
            my_size += 1 + 8;
        }
        if self.head_length != 0. {
            my_size += 1 + 8;
        }
        if self.head_diameter != 0. {
            my_size += 1 + 8;
        }
        if let Some(v) = self.color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pose.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if self.shaft_length != 0. {
            os.write_double(2, self.shaft_length)?;
        }
        if self.shaft_diameter != 0. {
            os.write_double(3, self.shaft_diameter)?;
        }
        if self.head_length != 0. {
            os.write_double(4, self.head_length)?;
        }
        if self.head_diameter != 0. {
            os.write_double(5, self.head_diameter)?;
        }
        if let Some(v) = self.color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ArrowPrimitive {
        ArrowPrimitive::new()
    }

    fn clear(&mut self) {
        self.pose.clear();
        self.shaft_length = 0.;
        self.shaft_diameter = 0.;
        self.head_length = 0.;
        self.head_diameter = 0.;
        self.color.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ArrowPrimitive {
        static instance: ArrowPrimitive = ArrowPrimitive {
            pose: ::protobuf::MessageField::none(),
            shaft_length: 0.,
            shaft_diameter: 0.,
            head_length: 0.,
            head_diameter: 0.,
            color: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ArrowPrimitive {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ArrowPrimitive").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ArrowPrimitive {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ArrowPrimitive {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dfoxglove/ArrowPrimitive.proto\x12\x08foxglove\x1a\x14foxglove/Colo\
    r.proto\x1a\x13foxglove/Pose.proto\"\xeb\x01\n\x0eArrowPrimitive\x12\"\n\
    \x04pose\x18\x01\x20\x01(\x0b2\x0e.foxglove.PoseR\x04pose\x12!\n\x0cshaf\
    t_length\x18\x02\x20\x01(\x01R\x0bshaftLength\x12%\n\x0eshaft_diameter\
    \x18\x03\x20\x01(\x01R\rshaftDiameter\x12\x1f\n\x0bhead_length\x18\x04\
    \x20\x01(\x01R\nheadLength\x12#\n\rhead_diameter\x18\x05\x20\x01(\x01R\
    \x0cheadDiameter\x12%\n\x05color\x18\x06\x20\x01(\x0b2\x0f.foxglove.Colo\
    rR\x05colorb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::Color::file_descriptor().clone());
            deps.push(super::Pose::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ArrowPrimitive::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
