// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/CircleAnnotation.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.CircleAnnotation)
pub struct CircleAnnotation {
    // message fields
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.timestamp)
    pub timestamp: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.position)
    pub position: ::protobuf::MessageField<super::Point2::Point2>,
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.diameter)
    pub diameter: f64,
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.thickness)
    pub thickness: f64,
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.fill_color)
    pub fill_color: ::protobuf::MessageField<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.CircleAnnotation.outline_color)
    pub outline_color: ::protobuf::MessageField<super::Color::Color>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.CircleAnnotation.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CircleAnnotation {
    fn default() -> &'a CircleAnnotation {
        <CircleAnnotation as ::protobuf::Message>::default_instance()
    }
}

impl CircleAnnotation {
    pub fn new() -> CircleAnnotation {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "timestamp",
            |m: &CircleAnnotation| { &m.timestamp },
            |m: &mut CircleAnnotation| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Point2::Point2>(
            "position",
            |m: &CircleAnnotation| { &m.position },
            |m: &mut CircleAnnotation| { &mut m.position },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "diameter",
            |m: &CircleAnnotation| { &m.diameter },
            |m: &mut CircleAnnotation| { &mut m.diameter },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "thickness",
            |m: &CircleAnnotation| { &m.thickness },
            |m: &mut CircleAnnotation| { &mut m.thickness },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "fill_color",
            |m: &CircleAnnotation| { &m.fill_color },
            |m: &mut CircleAnnotation| { &mut m.fill_color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "outline_color",
            |m: &CircleAnnotation| { &m.outline_color },
            |m: &mut CircleAnnotation| { &mut m.outline_color },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CircleAnnotation>(
            "CircleAnnotation",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CircleAnnotation {
    const NAME: &'static str = "CircleAnnotation";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.timestamp)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.position)?;
                },
                25 => {
                    self.diameter = is.read_double()?;
                },
                33 => {
                    self.thickness = is.read_double()?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.fill_color)?;
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.outline_color)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.position.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.diameter != 0. {
            my_size += 1 + 8;
        }
        if self.thickness != 0. {
            my_size += 1 + 8;
        }
        if let Some(v) = self.fill_color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.outline_color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.timestamp.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.position.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if self.diameter != 0. {
            os.write_double(3, self.diameter)?;
        }
        if self.thickness != 0. {
            os.write_double(4, self.thickness)?;
        }
        if let Some(v) = self.fill_color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        if let Some(v) = self.outline_color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CircleAnnotation {
        CircleAnnotation::new()
    }

    fn clear(&mut self) {
        self.timestamp.clear();
        self.position.clear();
        self.diameter = 0.;
        self.thickness = 0.;
        self.fill_color.clear();
        self.outline_color.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CircleAnnotation {
        static instance: CircleAnnotation = CircleAnnotation {
            timestamp: ::protobuf::MessageField::none(),
            position: ::protobuf::MessageField::none(),
            diameter: 0.,
            thickness: 0.,
            fill_color: ::protobuf::MessageField::none(),
            outline_color: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CircleAnnotation {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CircleAnnotation").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CircleAnnotation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CircleAnnotation {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ffoxglove/CircleAnnotation.proto\x12\x08foxglove\x1a\x14foxglove/Co\
    lor.proto\x1a\x15foxglove/Point2.proto\x1a\x1fgoogle/protobuf/timestamp.\
    proto\"\x9a\x02\n\x10CircleAnnotation\x128\n\ttimestamp\x18\x01\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\ttimestamp\x12,\n\x08position\x18\
    \x02\x20\x01(\x0b2\x10.foxglove.Point2R\x08position\x12\x1a\n\x08diamete\
    r\x18\x03\x20\x01(\x01R\x08diameter\x12\x1c\n\tthickness\x18\x04\x20\x01\
    (\x01R\tthickness\x12.\n\nfill_color\x18\x05\x20\x01(\x0b2\x0f.foxglove.\
    ColorR\tfillColor\x124\n\routline_color\x18\x06\x20\x01(\x0b2\x0f.foxglo\
    ve.ColorR\x0coutlineColorb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::Color::file_descriptor().clone());
            deps.push(super::Point2::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(CircleAnnotation::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
