// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/FrameTransform.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.FrameTransform)
pub struct FrameTransform {
    // message fields
    // @@protoc_insertion_point(field:foxglove.FrameTransform.timestamp)
    pub timestamp: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:foxglove.FrameTransform.parent_frame_id)
    pub parent_frame_id: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.FrameTransform.child_frame_id)
    pub child_frame_id: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.FrameTransform.translation)
    pub translation: ::protobuf::MessageField<super::Vector3::Vector3>,
    // @@protoc_insertion_point(field:foxglove.FrameTransform.rotation)
    pub rotation: ::protobuf::MessageField<super::Quaternion::Quaternion>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.FrameTransform.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FrameTransform {
    fn default() -> &'a FrameTransform {
        <FrameTransform as ::protobuf::Message>::default_instance()
    }
}

impl FrameTransform {
    pub fn new() -> FrameTransform {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "timestamp",
            |m: &FrameTransform| { &m.timestamp },
            |m: &mut FrameTransform| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "parent_frame_id",
            |m: &FrameTransform| { &m.parent_frame_id },
            |m: &mut FrameTransform| { &mut m.parent_frame_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "child_frame_id",
            |m: &FrameTransform| { &m.child_frame_id },
            |m: &mut FrameTransform| { &mut m.child_frame_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Vector3::Vector3>(
            "translation",
            |m: &FrameTransform| { &m.translation },
            |m: &mut FrameTransform| { &mut m.translation },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Quaternion::Quaternion>(
            "rotation",
            |m: &FrameTransform| { &m.rotation },
            |m: &mut FrameTransform| { &mut m.rotation },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FrameTransform>(
            "FrameTransform",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FrameTransform {
    const NAME: &'static str = "FrameTransform";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.timestamp)?;
                },
                18 => {
                    self.parent_frame_id = is.read_string()?;
                },
                26 => {
                    self.child_frame_id = is.read_string()?;
                },
                34 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.translation)?;
                },
                42 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.rotation)?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.parent_frame_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.parent_frame_id);
        }
        if !self.child_frame_id.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.child_frame_id);
        }
        if let Some(v) = self.translation.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.rotation.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.timestamp.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.parent_frame_id.is_empty() {
            os.write_string(2, &self.parent_frame_id)?;
        }
        if !self.child_frame_id.is_empty() {
            os.write_string(3, &self.child_frame_id)?;
        }
        if let Some(v) = self.translation.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        }
        if let Some(v) = self.rotation.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FrameTransform {
        FrameTransform::new()
    }

    fn clear(&mut self) {
        self.timestamp.clear();
        self.parent_frame_id.clear();
        self.child_frame_id.clear();
        self.translation.clear();
        self.rotation.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FrameTransform {
        static instance: FrameTransform = FrameTransform {
            timestamp: ::protobuf::MessageField::none(),
            parent_frame_id: ::std::string::String::new(),
            child_frame_id: ::std::string::String::new(),
            translation: ::protobuf::MessageField::none(),
            rotation: ::protobuf::MessageField::none(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FrameTransform {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FrameTransform").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FrameTransform {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FrameTransform {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dfoxglove/FrameTransform.proto\x12\x08foxglove\x1a\x19foxglove/Quat\
    ernion.proto\x1a\x16foxglove/Vector3.proto\x1a\x1fgoogle/protobuf/timest\
    amp.proto\"\xff\x01\n\x0eFrameTransform\x128\n\ttimestamp\x18\x01\x20\
    \x01(\x0b2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n\x0fparent_fr\
    ame_id\x18\x02\x20\x01(\tR\rparentFrameId\x12$\n\x0echild_frame_id\x18\
    \x03\x20\x01(\tR\x0cchildFrameId\x123\n\x0btranslation\x18\x04\x20\x01(\
    \x0b2\x11.foxglove.Vector3R\x0btranslation\x120\n\x08rotation\x18\x05\
    \x20\x01(\x0b2\x14.foxglove.QuaternionR\x08rotationb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::Quaternion::file_descriptor().clone());
            deps.push(super::Vector3::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(FrameTransform::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
