// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/LaserScan.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.LaserScan)
pub struct LaserScan {
    // message fields
    // @@protoc_insertion_point(field:foxglove.LaserScan.timestamp)
    pub timestamp: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:foxglove.LaserScan.frame_id)
    pub frame_id: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.LaserScan.pose)
    pub pose: ::protobuf::MessageField<super::Pose::Pose>,
    // @@protoc_insertion_point(field:foxglove.LaserScan.start_angle)
    pub start_angle: f64,
    // @@protoc_insertion_point(field:foxglove.LaserScan.end_angle)
    pub end_angle: f64,
    // @@protoc_insertion_point(field:foxglove.LaserScan.ranges)
    pub ranges: ::std::vec::Vec<f64>,
    // @@protoc_insertion_point(field:foxglove.LaserScan.intensities)
    pub intensities: ::std::vec::Vec<f64>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.LaserScan.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LaserScan {
    fn default() -> &'a LaserScan {
        <LaserScan as ::protobuf::Message>::default_instance()
    }
}

impl LaserScan {
    pub fn new() -> LaserScan {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "timestamp",
            |m: &LaserScan| { &m.timestamp },
            |m: &mut LaserScan| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "frame_id",
            |m: &LaserScan| { &m.frame_id },
            |m: &mut LaserScan| { &mut m.frame_id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Pose::Pose>(
            "pose",
            |m: &LaserScan| { &m.pose },
            |m: &mut LaserScan| { &mut m.pose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "start_angle",
            |m: &LaserScan| { &m.start_angle },
            |m: &mut LaserScan| { &mut m.start_angle },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "end_angle",
            |m: &LaserScan| { &m.end_angle },
            |m: &mut LaserScan| { &mut m.end_angle },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "ranges",
            |m: &LaserScan| { &m.ranges },
            |m: &mut LaserScan| { &mut m.ranges },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "intensities",
            |m: &LaserScan| { &m.intensities },
            |m: &mut LaserScan| { &mut m.intensities },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LaserScan>(
            "LaserScan",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LaserScan {
    const NAME: &'static str = "LaserScan";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.timestamp)?;
                },
                18 => {
                    self.frame_id = is.read_string()?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pose)?;
                },
                33 => {
                    self.start_angle = is.read_double()?;
                },
                41 => {
                    self.end_angle = is.read_double()?;
                },
                50 => {
                    is.read_repeated_packed_double_into(&mut self.ranges)?;
                },
                49 => {
                    self.ranges.push(is.read_double()?);
                },
                58 => {
                    is.read_repeated_packed_double_into(&mut self.intensities)?;
                },
                57 => {
                    self.intensities.push(is.read_double()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.frame_id.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.frame_id);
        }
        if let Some(v) = self.pose.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.start_angle != 0. {
            my_size += 1 + 8;
        }
        if self.end_angle != 0. {
            my_size += 1 + 8;
        }
        my_size += 9 * self.ranges.len() as u64;
        my_size += 9 * self.intensities.len() as u64;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.timestamp.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.frame_id.is_empty() {
            os.write_string(2, &self.frame_id)?;
        }
        if let Some(v) = self.pose.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.start_angle != 0. {
            os.write_double(4, self.start_angle)?;
        }
        if self.end_angle != 0. {
            os.write_double(5, self.end_angle)?;
        }
        for v in &self.ranges {
            os.write_double(6, *v)?;
        };
        for v in &self.intensities {
            os.write_double(7, *v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LaserScan {
        LaserScan::new()
    }

    fn clear(&mut self) {
        self.timestamp.clear();
        self.frame_id.clear();
        self.pose.clear();
        self.start_angle = 0.;
        self.end_angle = 0.;
        self.ranges.clear();
        self.intensities.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LaserScan {
        static instance: LaserScan = LaserScan {
            timestamp: ::protobuf::MessageField::none(),
            frame_id: ::std::string::String::new(),
            pose: ::protobuf::MessageField::none(),
            start_angle: 0.,
            end_angle: 0.,
            ranges: ::std::vec::Vec::new(),
            intensities: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LaserScan {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LaserScan").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LaserScan {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LaserScan {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18foxglove/LaserScan.proto\x12\x08foxglove\x1a\x13foxglove/Pose.prot\
    o\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n\tLaserScan\x128\n\t\
    timestamp\x18\x01\x20\x01(\x0b2\x1a.google.protobuf.TimestampR\ttimestam\
    p\x12\x19\n\x08frame_id\x18\x02\x20\x01(\tR\x07frameId\x12\"\n\x04pose\
    \x18\x03\x20\x01(\x0b2\x0e.foxglove.PoseR\x04pose\x12\x1f\n\x0bstart_ang\
    le\x18\x04\x20\x01(\x01R\nstartAngle\x12\x1b\n\tend_angle\x18\x05\x20\
    \x01(\x01R\x08endAngle\x12\x16\n\x06ranges\x18\x06\x20\x03(\x01R\x06rang\
    es\x12\x20\n\x0bintensities\x18\x07\x20\x03(\x01R\x0bintensitiesb\x06pro\
    to3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(2);
            deps.push(super::Pose::file_descriptor().clone());
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LaserScan::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
