// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/LinePrimitive.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.LinePrimitive)
pub struct LinePrimitive {
    // message fields
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.type)
    pub type_: ::protobuf::EnumOrUnknown<line_primitive::Type>,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.pose)
    pub pose: ::protobuf::MessageField<super::Pose::Pose>,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.thickness)
    pub thickness: f64,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.scale_invariant)
    pub scale_invariant: bool,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.points)
    pub points: ::std::vec::Vec<super::Point3::Point3>,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.color)
    pub color: ::protobuf::MessageField<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.colors)
    pub colors: ::std::vec::Vec<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.LinePrimitive.indices)
    pub indices: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.LinePrimitive.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LinePrimitive {
    fn default() -> &'a LinePrimitive {
        <LinePrimitive as ::protobuf::Message>::default_instance()
    }
}

impl LinePrimitive {
    pub fn new() -> LinePrimitive {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(8);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &LinePrimitive| { &m.type_ },
            |m: &mut LinePrimitive| { &mut m.type_ },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Pose::Pose>(
            "pose",
            |m: &LinePrimitive| { &m.pose },
            |m: &mut LinePrimitive| { &mut m.pose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "thickness",
            |m: &LinePrimitive| { &m.thickness },
            |m: &mut LinePrimitive| { &mut m.thickness },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "scale_invariant",
            |m: &LinePrimitive| { &m.scale_invariant },
            |m: &mut LinePrimitive| { &mut m.scale_invariant },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "points",
            |m: &LinePrimitive| { &m.points },
            |m: &mut LinePrimitive| { &mut m.points },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "color",
            |m: &LinePrimitive| { &m.color },
            |m: &mut LinePrimitive| { &mut m.color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "colors",
            |m: &LinePrimitive| { &m.colors },
            |m: &mut LinePrimitive| { &mut m.colors },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "indices",
            |m: &LinePrimitive| { &m.indices },
            |m: &mut LinePrimitive| { &mut m.indices },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LinePrimitive>(
            "LinePrimitive",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LinePrimitive {
    const NAME: &'static str = "LinePrimitive";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pose)?;
                },
                25 => {
                    self.thickness = is.read_double()?;
                },
                32 => {
                    self.scale_invariant = is.read_bool()?;
                },
                42 => {
                    self.points.push(is.read_message()?);
                },
                50 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color)?;
                },
                58 => {
                    self.colors.push(is.read_message()?);
                },
                66 => {
                    is.read_repeated_packed_fixed32_into(&mut self.indices)?;
                },
                69 => {
                    self.indices.push(is.read_fixed32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.type_ != ::protobuf::EnumOrUnknown::new(line_primitive::Type::LINE_STRIP) {
            my_size += ::protobuf::rt::int32_size(1, self.type_.value());
        }
        if let Some(v) = self.pose.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.thickness != 0. {
            my_size += 1 + 8;
        }
        if self.scale_invariant != false {
            my_size += 1 + 1;
        }
        for value in &self.points {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.colors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += 5 * self.indices.len() as u64;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.type_ != ::protobuf::EnumOrUnknown::new(line_primitive::Type::LINE_STRIP) {
            os.write_enum(1, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        if let Some(v) = self.pose.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if self.thickness != 0. {
            os.write_double(3, self.thickness)?;
        }
        if self.scale_invariant != false {
            os.write_bool(4, self.scale_invariant)?;
        }
        for v in &self.points {
            ::protobuf::rt::write_message_field_with_cached_size(5, v, os)?;
        };
        if let Some(v) = self.color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
        }
        for v in &self.colors {
            ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
        };
        for v in &self.indices {
            os.write_fixed32(8, *v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LinePrimitive {
        LinePrimitive::new()
    }

    fn clear(&mut self) {
        self.type_ = ::protobuf::EnumOrUnknown::new(line_primitive::Type::LINE_STRIP);
        self.pose.clear();
        self.thickness = 0.;
        self.scale_invariant = false;
        self.points.clear();
        self.color.clear();
        self.colors.clear();
        self.indices.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LinePrimitive {
        static instance: LinePrimitive = LinePrimitive {
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            pose: ::protobuf::MessageField::none(),
            thickness: 0.,
            scale_invariant: false,
            points: ::std::vec::Vec::new(),
            color: ::protobuf::MessageField::none(),
            colors: ::std::vec::Vec::new(),
            indices: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LinePrimitive {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LinePrimitive").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LinePrimitive {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LinePrimitive {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `LinePrimitive`
pub mod line_primitive {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:foxglove.LinePrimitive.Type)
    pub enum Type {
        // @@protoc_insertion_point(enum_value:foxglove.LinePrimitive.Type.LINE_STRIP)
        LINE_STRIP = 0,
        // @@protoc_insertion_point(enum_value:foxglove.LinePrimitive.Type.LINE_LOOP)
        LINE_LOOP = 1,
        // @@protoc_insertion_point(enum_value:foxglove.LinePrimitive.Type.LINE_LIST)
        LINE_LIST = 2,
    }

    impl ::protobuf::Enum for Type {
        const NAME: &'static str = "Type";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<Type> {
            match value {
                0 => ::std::option::Option::Some(Type::LINE_STRIP),
                1 => ::std::option::Option::Some(Type::LINE_LOOP),
                2 => ::std::option::Option::Some(Type::LINE_LIST),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [Type] = &[
            Type::LINE_STRIP,
            Type::LINE_LOOP,
            Type::LINE_LIST,
        ];
    }

    impl ::protobuf::EnumFull for Type {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("LinePrimitive.Type").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for Type {
        fn default() -> Self {
            Type::LINE_STRIP
        }
    }

    impl Type {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Type>("LinePrimitive.Type")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1cfoxglove/LinePrimitive.proto\x12\x08foxglove\x1a\x14foxglove/Color\
    .proto\x1a\x15foxglove/Point3.proto\x1a\x13foxglove/Pose.proto\"\xf6\x02\
    \n\rLinePrimitive\x120\n\x04type\x18\x01\x20\x01(\x0e2\x1c.foxglove.Line\
    Primitive.TypeR\x04type\x12\"\n\x04pose\x18\x02\x20\x01(\x0b2\x0e.foxglo\
    ve.PoseR\x04pose\x12\x1c\n\tthickness\x18\x03\x20\x01(\x01R\tthickness\
    \x12'\n\x0fscale_invariant\x18\x04\x20\x01(\x08R\x0escaleInvariant\x12(\
    \n\x06points\x18\x05\x20\x03(\x0b2\x10.foxglove.Point3R\x06points\x12%\n\
    \x05color\x18\x06\x20\x01(\x0b2\x0f.foxglove.ColorR\x05color\x12'\n\x06c\
    olors\x18\x07\x20\x03(\x0b2\x0f.foxglove.ColorR\x06colors\x12\x18\n\x07i\
    ndices\x18\x08\x20\x03(\x07R\x07indices\"4\n\x04Type\x12\x0e\n\nLINE_STR\
    IP\x10\0\x12\r\n\tLINE_LOOP\x10\x01\x12\r\n\tLINE_LIST\x10\x02b\x06proto\
    3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::Color::file_descriptor().clone());
            deps.push(super::Point3::file_descriptor().clone());
            deps.push(super::Pose::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(LinePrimitive::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(line_primitive::Type::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
