// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/ModelPrimitive.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.ModelPrimitive)
pub struct ModelPrimitive {
    // message fields
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.pose)
    pub pose: ::protobuf::MessageField<super::Pose::Pose>,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.scale)
    pub scale: ::protobuf::MessageField<super::Vector3::Vector3>,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.color)
    pub color: ::protobuf::MessageField<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.override_color)
    pub override_color: bool,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.url)
    pub url: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.media_type)
    pub media_type: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.ModelPrimitive.data)
    pub data: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.ModelPrimitive.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ModelPrimitive {
    fn default() -> &'a ModelPrimitive {
        <ModelPrimitive as ::protobuf::Message>::default_instance()
    }
}

impl ModelPrimitive {
    pub fn new() -> ModelPrimitive {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(7);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Pose::Pose>(
            "pose",
            |m: &ModelPrimitive| { &m.pose },
            |m: &mut ModelPrimitive| { &mut m.pose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Vector3::Vector3>(
            "scale",
            |m: &ModelPrimitive| { &m.scale },
            |m: &mut ModelPrimitive| { &mut m.scale },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "color",
            |m: &ModelPrimitive| { &m.color },
            |m: &mut ModelPrimitive| { &mut m.color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "override_color",
            |m: &ModelPrimitive| { &m.override_color },
            |m: &mut ModelPrimitive| { &mut m.override_color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "url",
            |m: &ModelPrimitive| { &m.url },
            |m: &mut ModelPrimitive| { &mut m.url },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "media_type",
            |m: &ModelPrimitive| { &m.media_type },
            |m: &mut ModelPrimitive| { &mut m.media_type },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &ModelPrimitive| { &m.data },
            |m: &mut ModelPrimitive| { &mut m.data },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ModelPrimitive>(
            "ModelPrimitive",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ModelPrimitive {
    const NAME: &'static str = "ModelPrimitive";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pose)?;
                },
                18 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.scale)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color)?;
                },
                32 => {
                    self.override_color = is.read_bool()?;
                },
                42 => {
                    self.url = is.read_string()?;
                },
                50 => {
                    self.media_type = is.read_string()?;
                },
                58 => {
                    self.data = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pose.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.scale.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if let Some(v) = self.color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if self.override_color != false {
            my_size += 1 + 1;
        }
        if !self.url.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.url);
        }
        if !self.media_type.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.media_type);
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(7, &self.data);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pose.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if let Some(v) = self.scale.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        }
        if let Some(v) = self.color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        if self.override_color != false {
            os.write_bool(4, self.override_color)?;
        }
        if !self.url.is_empty() {
            os.write_string(5, &self.url)?;
        }
        if !self.media_type.is_empty() {
            os.write_string(6, &self.media_type)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(7, &self.data)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ModelPrimitive {
        ModelPrimitive::new()
    }

    fn clear(&mut self) {
        self.pose.clear();
        self.scale.clear();
        self.color.clear();
        self.override_color = false;
        self.url.clear();
        self.media_type.clear();
        self.data.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ModelPrimitive {
        static instance: ModelPrimitive = ModelPrimitive {
            pose: ::protobuf::MessageField::none(),
            scale: ::protobuf::MessageField::none(),
            color: ::protobuf::MessageField::none(),
            override_color: false,
            url: ::std::string::String::new(),
            media_type: ::std::string::String::new(),
            data: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ModelPrimitive {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ModelPrimitive").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ModelPrimitive {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ModelPrimitive {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1dfoxglove/ModelPrimitive.proto\x12\x08foxglove\x1a\x14foxglove/Colo\
    r.proto\x1a\x13foxglove/Pose.proto\x1a\x16foxglove/Vector3.proto\"\xf0\
    \x01\n\x0eModelPrimitive\x12\"\n\x04pose\x18\x01\x20\x01(\x0b2\x0e.foxgl\
    ove.PoseR\x04pose\x12'\n\x05scale\x18\x02\x20\x01(\x0b2\x11.foxglove.Vec\
    tor3R\x05scale\x12%\n\x05color\x18\x03\x20\x01(\x0b2\x0f.foxglove.ColorR\
    \x05color\x12%\n\x0eoverride_color\x18\x04\x20\x01(\x08R\roverrideColor\
    \x12\x10\n\x03url\x18\x05\x20\x01(\tR\x03url\x12\x1d\n\nmedia_type\x18\
    \x06\x20\x01(\tR\tmediaType\x12\x12\n\x04data\x18\x07\x20\x01(\x0cR\x04d\
    atab\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::Color::file_descriptor().clone());
            deps.push(super::Pose::file_descriptor().clone());
            deps.push(super::Vector3::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(ModelPrimitive::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
