// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/PackedElementField.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.PackedElementField)
pub struct PackedElementField {
    // message fields
    // @@protoc_insertion_point(field:foxglove.PackedElementField.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.PackedElementField.offset)
    pub offset: u32,
    // @@protoc_insertion_point(field:foxglove.PackedElementField.type)
    pub type_: ::protobuf::EnumOrUnknown<packed_element_field::NumericType>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.PackedElementField.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PackedElementField {
    fn default() -> &'a PackedElementField {
        <PackedElementField as ::protobuf::Message>::default_instance()
    }
}

impl PackedElementField {
    pub fn new() -> PackedElementField {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &PackedElementField| { &m.name },
            |m: &mut PackedElementField| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "offset",
            |m: &PackedElementField| { &m.offset },
            |m: &mut PackedElementField| { &mut m.offset },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "type",
            |m: &PackedElementField| { &m.type_ },
            |m: &mut PackedElementField| { &mut m.type_ },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PackedElementField>(
            "PackedElementField",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PackedElementField {
    const NAME: &'static str = "PackedElementField";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                21 => {
                    self.offset = is.read_fixed32()?;
                },
                24 => {
                    self.type_ = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if self.offset != 0 {
            my_size += 1 + 4;
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(packed_element_field::NumericType::UNKNOWN) {
            my_size += ::protobuf::rt::int32_size(3, self.type_.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if self.offset != 0 {
            os.write_fixed32(2, self.offset)?;
        }
        if self.type_ != ::protobuf::EnumOrUnknown::new(packed_element_field::NumericType::UNKNOWN) {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&self.type_))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PackedElementField {
        PackedElementField::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.offset = 0;
        self.type_ = ::protobuf::EnumOrUnknown::new(packed_element_field::NumericType::UNKNOWN);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PackedElementField {
        static instance: PackedElementField = PackedElementField {
            name: ::std::string::String::new(),
            offset: 0,
            type_: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PackedElementField {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PackedElementField").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PackedElementField {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PackedElementField {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `PackedElementField`
pub mod packed_element_field {
    #[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
    // @@protoc_insertion_point(enum:foxglove.PackedElementField.NumericType)
    pub enum NumericType {
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.UNKNOWN)
        UNKNOWN = 0,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.UINT8)
        UINT8 = 1,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.INT8)
        INT8 = 2,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.UINT16)
        UINT16 = 3,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.INT16)
        INT16 = 4,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.UINT32)
        UINT32 = 5,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.INT32)
        INT32 = 6,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.FLOAT32)
        FLOAT32 = 7,
        // @@protoc_insertion_point(enum_value:foxglove.PackedElementField.NumericType.FLOAT64)
        FLOAT64 = 8,
    }

    impl ::protobuf::Enum for NumericType {
        const NAME: &'static str = "NumericType";

        fn value(&self) -> i32 {
            *self as i32
        }

        fn from_i32(value: i32) -> ::std::option::Option<NumericType> {
            match value {
                0 => ::std::option::Option::Some(NumericType::UNKNOWN),
                1 => ::std::option::Option::Some(NumericType::UINT8),
                2 => ::std::option::Option::Some(NumericType::INT8),
                3 => ::std::option::Option::Some(NumericType::UINT16),
                4 => ::std::option::Option::Some(NumericType::INT16),
                5 => ::std::option::Option::Some(NumericType::UINT32),
                6 => ::std::option::Option::Some(NumericType::INT32),
                7 => ::std::option::Option::Some(NumericType::FLOAT32),
                8 => ::std::option::Option::Some(NumericType::FLOAT64),
                _ => ::std::option::Option::None
            }
        }

        const VALUES: &'static [NumericType] = &[
            NumericType::UNKNOWN,
            NumericType::UINT8,
            NumericType::INT8,
            NumericType::UINT16,
            NumericType::INT16,
            NumericType::UINT32,
            NumericType::INT32,
            NumericType::FLOAT32,
            NumericType::FLOAT64,
        ];
    }

    impl ::protobuf::EnumFull for NumericType {
        fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().enum_by_package_relative_name("PackedElementField.NumericType").unwrap()).clone()
        }

        fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
            let index = *self as usize;
            Self::enum_descriptor().value_by_index(index)
        }
    }

    impl ::std::default::Default for NumericType {
        fn default() -> Self {
            NumericType::UNKNOWN
        }
    }

    impl NumericType {
        pub(in super) fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
            ::protobuf::reflect::GeneratedEnumDescriptorData::new::<NumericType>("PackedElementField.NumericType")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n!foxglove/PackedElementField.proto\x12\x08foxglove\"\xf7\x01\n\x12Pack\
    edElementField\x12\x12\n\x04name\x18\x01\x20\x01(\tR\x04name\x12\x16\n\
    \x06offset\x18\x02\x20\x01(\x07R\x06offset\x12<\n\x04type\x18\x03\x20\
    \x01(\x0e2(.foxglove.PackedElementField.NumericTypeR\x04type\"w\n\x0bNum\
    ericType\x12\x0b\n\x07UNKNOWN\x10\0\x12\t\n\x05UINT8\x10\x01\x12\x08\n\
    \x04INT8\x10\x02\x12\n\n\x06UINT16\x10\x03\x12\t\n\x05INT16\x10\x04\x12\
    \n\n\x06UINT32\x10\x05\x12\t\n\x05INT32\x10\x06\x12\x0b\n\x07FLOAT32\x10\
    \x07\x12\x0b\n\x07FLOAT64\x10\x08b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PackedElementField::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(packed_element_field::NumericType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
