// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/RawAudio.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:foxglove.RawAudio)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RawAudio {
    // message fields
    // @@protoc_insertion_point(field:foxglove.RawAudio.timestamp)
    pub timestamp: ::protobuf::MessageField<::protobuf::well_known_types::timestamp::Timestamp>,
    // @@protoc_insertion_point(field:foxglove.RawAudio.data)
    pub data: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:foxglove.RawAudio.format)
    pub format: ::std::string::String,
    // @@protoc_insertion_point(field:foxglove.RawAudio.sample_rate)
    pub sample_rate: u32,
    // @@protoc_insertion_point(field:foxglove.RawAudio.number_of_channels)
    pub number_of_channels: u32,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.RawAudio.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RawAudio {
    fn default() -> &'a RawAudio {
        <RawAudio as ::protobuf::Message>::default_instance()
    }
}

impl RawAudio {
    pub fn new() -> RawAudio {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, ::protobuf::well_known_types::timestamp::Timestamp>(
            "timestamp",
            |m: &RawAudio| { &m.timestamp },
            |m: &mut RawAudio| { &mut m.timestamp },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "data",
            |m: &RawAudio| { &m.data },
            |m: &mut RawAudio| { &mut m.data },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "format",
            |m: &RawAudio| { &m.format },
            |m: &mut RawAudio| { &mut m.format },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sample_rate",
            |m: &RawAudio| { &m.sample_rate },
            |m: &mut RawAudio| { &mut m.sample_rate },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "number_of_channels",
            |m: &RawAudio| { &m.number_of_channels },
            |m: &mut RawAudio| { &mut m.number_of_channels },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RawAudio>(
            "RawAudio",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RawAudio {
    const NAME: &'static str = "RawAudio";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.timestamp)?;
                },
                18 => {
                    self.data = is.read_bytes()?;
                },
                26 => {
                    self.format = is.read_string()?;
                },
                37 => {
                    self.sample_rate = is.read_fixed32()?;
                },
                45 => {
                    self.number_of_channels = is.read_fixed32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.timestamp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        if !self.data.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data);
        }
        if !self.format.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.format);
        }
        if self.sample_rate != 0 {
            my_size += 1 + 4;
        }
        if self.number_of_channels != 0 {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.timestamp.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        if !self.data.is_empty() {
            os.write_bytes(2, &self.data)?;
        }
        if !self.format.is_empty() {
            os.write_string(3, &self.format)?;
        }
        if self.sample_rate != 0 {
            os.write_fixed32(4, self.sample_rate)?;
        }
        if self.number_of_channels != 0 {
            os.write_fixed32(5, self.number_of_channels)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RawAudio {
        RawAudio::new()
    }

    fn clear(&mut self) {
        self.timestamp.clear();
        self.data.clear();
        self.format.clear();
        self.sample_rate = 0;
        self.number_of_channels = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RawAudio {
        static instance: RawAudio = RawAudio {
            timestamp: ::protobuf::MessageField::none(),
            data: ::std::vec::Vec::new(),
            format: ::std::string::String::new(),
            sample_rate: 0,
            number_of_channels: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RawAudio {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RawAudio").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RawAudio {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RawAudio {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17foxglove/RawAudio.proto\x12\x08foxglove\x1a\x1fgoogle/protobuf/tim\
    estamp.proto\"\xbf\x01\n\x08RawAudio\x128\n\ttimestamp\x18\x01\x20\x01(\
    \x0b2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n\x04data\x18\
    \x02\x20\x01(\x0cR\x04data\x12\x16\n\x06format\x18\x03\x20\x01(\tR\x06fo\
    rmat\x12\x1f\n\x0bsample_rate\x18\x04\x20\x01(\x07R\nsampleRate\x12,\n\
    \x12number_of_channels\x18\x05\x20\x01(\x07R\x10numberOfChannelsb\x06pro\
    to3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::well_known_types::timestamp::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(RawAudio::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
