// This file is generated by rust-protobuf 3.2.0. Do not edit
// .proto file is parsed by protoc 3.12.4
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `foxglove/TriangleListPrimitive.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_2_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:foxglove.TriangleListPrimitive)
pub struct TriangleListPrimitive {
    // message fields
    // @@protoc_insertion_point(field:foxglove.TriangleListPrimitive.pose)
    pub pose: ::protobuf::MessageField<super::Pose::Pose>,
    // @@protoc_insertion_point(field:foxglove.TriangleListPrimitive.points)
    pub points: ::std::vec::Vec<super::Point3::Point3>,
    // @@protoc_insertion_point(field:foxglove.TriangleListPrimitive.color)
    pub color: ::protobuf::MessageField<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.TriangleListPrimitive.colors)
    pub colors: ::std::vec::Vec<super::Color::Color>,
    // @@protoc_insertion_point(field:foxglove.TriangleListPrimitive.indices)
    pub indices: ::std::vec::Vec<u32>,
    // special fields
    // @@protoc_insertion_point(special_field:foxglove.TriangleListPrimitive.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TriangleListPrimitive {
    fn default() -> &'a TriangleListPrimitive {
        <TriangleListPrimitive as ::protobuf::Message>::default_instance()
    }
}

impl TriangleListPrimitive {
    pub fn new() -> TriangleListPrimitive {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Pose::Pose>(
            "pose",
            |m: &TriangleListPrimitive| { &m.pose },
            |m: &mut TriangleListPrimitive| { &mut m.pose },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "points",
            |m: &TriangleListPrimitive| { &m.points },
            |m: &mut TriangleListPrimitive| { &mut m.points },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_message_field_accessor::<_, super::Color::Color>(
            "color",
            |m: &TriangleListPrimitive| { &m.color },
            |m: &mut TriangleListPrimitive| { &mut m.color },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "colors",
            |m: &TriangleListPrimitive| { &m.colors },
            |m: &mut TriangleListPrimitive| { &mut m.colors },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "indices",
            |m: &TriangleListPrimitive| { &m.indices },
            |m: &mut TriangleListPrimitive| { &mut m.indices },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TriangleListPrimitive>(
            "TriangleListPrimitive",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TriangleListPrimitive {
    const NAME: &'static str = "TriangleListPrimitive";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.pose)?;
                },
                18 => {
                    self.points.push(is.read_message()?);
                },
                26 => {
                    ::protobuf::rt::read_singular_message_into_field(is, &mut self.color)?;
                },
                34 => {
                    self.colors.push(is.read_message()?);
                },
                42 => {
                    is.read_repeated_packed_fixed32_into(&mut self.indices)?;
                },
                45 => {
                    self.indices.push(is.read_fixed32()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.pose.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.points {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        if let Some(v) = self.color.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        }
        for value in &self.colors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += 5 * self.indices.len() as u64;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.pose.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        }
        for v in &self.points {
            ::protobuf::rt::write_message_field_with_cached_size(2, v, os)?;
        };
        if let Some(v) = self.color.as_ref() {
            ::protobuf::rt::write_message_field_with_cached_size(3, v, os)?;
        }
        for v in &self.colors {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        for v in &self.indices {
            os.write_fixed32(5, *v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TriangleListPrimitive {
        TriangleListPrimitive::new()
    }

    fn clear(&mut self) {
        self.pose.clear();
        self.points.clear();
        self.color.clear();
        self.colors.clear();
        self.indices.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TriangleListPrimitive {
        static instance: TriangleListPrimitive = TriangleListPrimitive {
            pose: ::protobuf::MessageField::none(),
            points: ::std::vec::Vec::new(),
            color: ::protobuf::MessageField::none(),
            colors: ::std::vec::Vec::new(),
            indices: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TriangleListPrimitive {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TriangleListPrimitive").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TriangleListPrimitive {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TriangleListPrimitive {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n$foxglove/TriangleListPrimitive.proto\x12\x08foxglove\x1a\x14foxglove/\
    Color.proto\x1a\x15foxglove/Point3.proto\x1a\x13foxglove/Pose.proto\"\
    \xcf\x01\n\x15TriangleListPrimitive\x12\"\n\x04pose\x18\x01\x20\x01(\x0b\
    2\x0e.foxglove.PoseR\x04pose\x12(\n\x06points\x18\x02\x20\x03(\x0b2\x10.\
    foxglove.Point3R\x06points\x12%\n\x05color\x18\x03\x20\x01(\x0b2\x0f.fox\
    glove.ColorR\x05color\x12'\n\x06colors\x18\x04\x20\x03(\x0b2\x0f.foxglov\
    e.ColorR\x06colors\x12\x18\n\x07indices\x18\x05\x20\x03(\x07R\x07indices\
    b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(3);
            deps.push(super::Color::file_descriptor().clone());
            deps.push(super::Point3::file_descriptor().clone());
            deps.push(super::Pose::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(TriangleListPrimitive::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
